### ISSUE TITLE
Add goals and status to README.md

### ISSUE THREAD

**Issue by poikilos** [FFT-Hackers/SisterRay#56]
I found this project only by chance, on the Qhimm Forums topic [Anyone familiar with the code base at this point?](http://forums.qhimm.com/index.php?topic=19494.0)
- Please explain which version or versions (PSX, 1998 PC, Steam) you are targeting.

- Perhaps also mention something about the status, or provide a link to an official forum/topic (and website, social media, etc, if any) if one exists. Is "SisterRay is powered by Cid and Mog" a joke? If so, consider putting it in quotes so it is not considered a confusing statement of fact. If it is a fact, consider making "Cid" and "Mog" into [markdown hyperlinks](https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet#links) to show what they mean.

Searching Google for: qhimm SisterRay

...doesn't even turn up much (except for a discussion saying you have a channel on Qhimm on Discord).

**Comment by quantumpencil** [comment]
Hello!

I'm not really ready to go public with the project yet, however when I start cutting releases I will update the readme and make announcements in public forums. 

Best,

Blake
